/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uchardet {
    _unused: [u8; 0],
}
#[doc = " A handle for a uchardet encoding detector."]
pub type uchardet_t = *mut uchardet;
unsafe extern "C" {
    #[doc = " Create an encoding detector.\n @return an instance of uchardet_t."]
    pub fn uchardet_new() -> uchardet_t;
}
unsafe extern "C" {
    #[doc = " Delete an encoding detector.\n @param ud [in] the uchardet_t handle to delete."]
    pub fn uchardet_delete(ud: uchardet_t);
}
unsafe extern "C" {
    #[doc = " Feed data to an encoding detector.\n The detector is able to shortcut processing when it reaches certainty\n for an encoding, so you should not worry about limiting input data.\n As far as you should be concerned: the more the better.\n\n @param ud [in] handle of an instance of uchardet\n @param data [in] data\n @param len [in] number of byte of data\n @return non-zero number on failure."]
    pub fn uchardet_handle_data(
        ud: uchardet_t,
        data: *const ::core::ffi::c_char,
        len: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Notify an end of data to an encoding detector.\n @param ud [in] handle of an instance of uchardet"]
    pub fn uchardet_data_end(ud: uchardet_t);
}
unsafe extern "C" {
    #[doc = " Reset an encoding detector.\n @param ud [in] handle of an instance of uchardet"]
    pub fn uchardet_reset(ud: uchardet_t);
}
unsafe extern "C" {
    #[doc = " Get an iconv-compatible name of the encoding that was detected.\n @param ud [in] handle of an instance of uchardet\n @return name of charset on success and \"\" on failure."]
    pub fn uchardet_get_charset(ud: uchardet_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn uchardet_get_n_candidates(ud: uchardet_t) -> usize;
}
unsafe extern "C" {
    pub fn uchardet_get_confidence(ud: uchardet_t, candidate: usize) -> f32;
}
unsafe extern "C" {
    pub fn uchardet_get_encoding(ud: uchardet_t, candidate: usize) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn uchardet_get_language(ud: uchardet_t, candidate: usize) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn uchardet_weigh_language(
        ud: uchardet_t,
        language: *const ::core::ffi::c_char,
        weight: f32,
    );
}
unsafe extern "C" {
    pub fn uchardet_set_default_weight(ud: uchardet_t, weight: f32);
}
